// Package index generates MEMORY.md from the frontmatter of the merged memories.
//
// The index is derived, never edited by hand. That is what removes the merge
// conflict every contributor would otherwise hit, since a shared hand-written
// index is touched by everyone who adds a memory.
package index

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Arlezz/memory-manager/internal/frontmatter"
	"github.com/Arlezz/memory-manager/internal/layer"
)

// Banner marks the file as derived. It is deliberately one line: the index is
// loaded into every session's context, so each extra line costs tokens forever.
const Banner = "<!-- Generated by memory-manager from each memory's frontmatter. Edits here are overwritten; edit the memory file instead. -->"

// sectionOrder controls the order of type sections. Identity and standing
// instructions come first because they change how the whole session behaves.
var sectionOrder = []string{"user", "feedback", "project", "reference"}

// sectionTitle is the heading shown for each type.
var sectionTitle = map[string]string{
	"user":      "Who the user is",
	"feedback":  "How to work",
	"project":   "Projects and constraints",
	"reference": "References",
}

// Render builds the index body for the given memories.
//
// Sections appear only when they have content. A memory whose type is unknown
// still gets listed, under "Other", so a format defect never hides a fact.
func Render(memories []frontmatter.Memory) string {
	byType := map[string][]frontmatter.Memory{}
	for _, m := range memories {
		key := m.Type
		if sectionTitle[key] == "" {
			key = "other"
		}
		byType[key] = append(byType[key], m)
	}
	for _, list := range byType {
		sort.Slice(list, func(i, j int) bool { return list[i].Base < list[j].Base })
	}

	var b strings.Builder
	b.WriteString(Banner + "\n")

	order := append(append([]string{}, sectionOrder...), "other")
	for _, key := range order {
		list := byType[key]
		if len(list) == 0 {
			continue
		}
		title := sectionTitle[key]
		if title == "" {
			title = "Other"
		}
		fmt.Fprintf(&b, "\n## %s\n\n", title)
		for _, m := range list {
			b.WriteString(line(m))
		}
	}
	return b.String()
}

// line renders one index entry: a link to the file plus its description.
func line(m frontmatter.Memory) string {
	label := m.Name
	if label == "" {
		label = strings.TrimSuffix(m.Base, filepath.Ext(m.Base))
	}
	desc := m.Description
	if desc == "" {
		desc = "(no description in frontmatter)"
	}
	return fmt.Sprintf("- [%s](%s) — %s\n", label, m.Base, desc)
}

// Write renders the index into dir/MEMORY.md.
func Write(dir string, memories []frontmatter.Memory) error {
	path := filepath.Join(dir, layer.IndexFile)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(Render(memories)), 0o644)
}
